### ISSUE TITLE
Doesn't actually install cuckoo

### ISSUE THREAD

**Issue by DigiAngel** [buguroo/cuckooautoinstall#6]
Topic says it...I tried this as root and I got:

```
root@siftworkstation:/home/build/cuckooautoinstall# bash cuckooautoinstall.sh 
┌─────────────────────────────────────────────────────────┐
│                CuckooAutoInstall 0.2                    │
│ David Reguera García - Dreg <dreguera@buguroo.com>      │
│ David Francos Cuartero - XayOn <dfrancos@buguroo.com>   │
│            Buguroo Offensive Security - 2015            │
└─────────────────────────────────────────────────────────┘
Logging enabled on /tmp/tmp.lVZrYe1aRa
✓ Getting virtualbox repo ready
✓ Installing packages volatility yara python-yara libyara3 libjansson4  and python-pip python-sqlalchemy mongodb python-bson python-dpkt python-jinja2 python-magic python-gridfs python-libvirt python-bottle python-pefile python-chardet git build-essential autoconf automake libtool dh-autoreconf libcurl4-gnutls-dev libmagic-dev python-dev tcpdump libcap2-bin virtualbox dkms python-pyrex
✓ pymongo
✓ Creating cuckoo user
✓ Cloning repositories
✓ Cloning cuckoo repository
✓ Fixing django problems on old versions
✓ Enabling mongodb in cuckoo
✓ Creating hostonly interface for cuckoo
✓ Setting capabilities
Segmentation fault (core dumped)
```

the file /tmp/tmp.lVZrYe1aRa is empty.  Searching for cuckoo gives me:

```
@siftworkstation:~/build/cuckooautoinstall$ locate cuckoo | grep -v cuckooauto
/home/cuckoo
/home/cuckoo/.bash_logout
/home/cuckoo/.bashrc
/home/cuckoo/.profile
/home/cuckoo/examples.desktop
/opt/remnux-ragpicker/processing/cuckooSandbox.py
/opt/remnux-ragpicker/processing/cuckooSandbox.yapsy-plugin
/opt/remnux-viper/modules/cuckoo.py
```

This is on Ubuntu 14.04.  Thank you.

**Comment by XayOn** [comment]
That segmentation fault happens sometimes setting the capabilities, should not affect the installation itself. What is not that normal is that /home/cuckoo/cuckoo is empty. 

Can you send the generated log or execute it with the verbose function?

As a personal advice, and as I see you've got quite a github profile on reporting bugs without making any effort yourself, read this: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by XayOn** [comment]
I was trying to use a variable with the user home glob magic ~foo
That ovbiously didn't work, fixed. 

Oh, and I need to document somewhere that sudo should be the recommended usage (so, call it as a normal user and it'll ask you your password), that way it does not segfault setting capabilities.

**Comment by DigiAngel** [comment]
Thank you...that worked well and has now installed...woo hoo!
