### ISSUE TITLE
"VirtualBox is running, please close it"

### ISSUE THREAD

**Issue by juliavdkris** [buguroo/cuckooautoinstall#8]
I'm on Ubuntu 16.10. I don't have VirtualBox open, and I can't find it in system monitor, so I don't think it's running on the background, either.

**Comment by rosehgal** [comment]
You cant directly run it. Need to kill/stop the vbox deamon:
`sudo service vboxdrv stop`

**Comment by XayOn** [comment]
Yep, have a look for "vboxsrv" process (ps aux|grep vboxsrv)

**Comment by SmilerRyan** [comment]
I've got a similar problem. I'm on Ubuntu 16.04LTS and cannot see VirtualBox in system monitor. Also, it says that it fails (Failed to stop vboxdrv.service: Unit vboxdrv.service not loaded.) when I try the previously mentioned (sudo service vboxdrv stop) stop command.

**Comment by ceremcem** [comment]
The `sudo service vboxdrv stop` command solved the issue also in Debian Buster.
